### ISSUE TITLE
Segmentation Fault with shared vertices models

### ISSUE THREAD

**Issue by elventian** [OGRECave/ogre-pagedgeometry#8]
If I pass model with shared vertices to addTree method of Forests::TreeLoader3D, I get Segmentation Fault at first call of Forests::PagedGeometry::update in BatchedGeometry::extractVertexDataFromShared at line:
```
// Release shared vertex data
  delete mesh->sharedVertexData;
```
Mesh: [pyramid.zip](https://github.com/OGRECave/ogre-pagedgeometry/files/2873046/pyramid.zip)

**Comment by Belsnickle** [comment]
![pyramids](https://user-images.githubusercontent.com/46137357/54057616-717cab00-41c1-11e9-99db-586478d8d89d.jpg)

I imported pyramid.mesh and material into my program.  First run my program closed and in the log it said it couldn't find the imposter image.  I ran it a second time and it seems to work as you can see in the screen shot.

Windows 10
Ogre 1.12
OpenGL

**Comment by Belsnickle** [comment]
I just found this thread while researching another issue:

https://forums.ogre3d.org/viewtopic.php?f=2&t=79636

**Comment by creadmefford** [comment]
fix submitted for review:
https://github.com/OGRECave/ogre-pagedgeometry/pull/10
